version: '3'

services:
  # varnish:
  #   image: varnish:${VARNISH_VERSION}
  #   ports:
  #     - ${VARNISH_PORT}:80
  #   links:
  #     - nginx

  nginx:
    image: nginx:alpine
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ./project:/var/www/project
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:cached
    environment:
      - PHP_FPM_PORT=${PHP_FPM_PORT}
    depends_on:
      - fpm

  fpm:
    build:
      context: php${PHP_VERSION}/fpm
      args:
        PHP_ENABLE_REDIS: ${PHP_ENABLE_REDIS}
        PHP_ENABLE_XDEBUG: ${PHP_ENABLE_XDEBUG}
    ports:
      - ${PHP_FPM_PORT}:9000
    volumes:
      - ./project:/var/www/project
    depends_on:
      - mariadb
      - redis
      - elasticsearch
      - rabbitmq
      - mailcatcher

  cli:
    build:
      context: php${PHP_VERSION}/cli
      args:
        NODE_VERSION: ${NODE_VERSION}
        PHP_ENABLE_REDIS: ${PHP_ENABLE_REDIS}
        PHP_ENABLE_XDEBUG: ${PHP_ENABLE_XDEBUG}
    working_dir: /var/www/project
    volumes:
      - ./project:/var/www/project
    depends_on:
      - mariadb
      - redis
      - elasticsearch
      - rabbitmq
      - mailcatcher
  
  mariadb:
    image: mariadb:${MARIADB_VERSION}
    ports:
      - ${MARIADB_PORT}:3306
    volumes:
      - ./data/mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MARIADB_DATABASE_NAME}
      # - MYSQL_USER=admin
      # - MYSQL_PASSWORD=admin
      - TERM=meh

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=mariadb
      # - PMA_ARBITRARY=1
    links:
      - mariadb
    ports:
      - ${PHPMYADMIN_PORT}:80

  redis:
    image: redis:${REDIS_VERSION}

  elasticsearch:
    image: elasticsearch:${ELASTICSEARCH_VERSION}
    tty: true
    environment:
      - cluster.name=docker-cluster
      - discovery.type=single-node
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms2048m -Xmx2048m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - './data/elasticsearch:/usr/share/elasticsearch/data'

  rabbitmq:
    image: rabbitmq:${RABBITMQ_VERSION}

  mailcatcher:
    image: sj26/mailcatcher
    ports:
      - ${MAILCATCHER_PORT}:1080
