name: Docker Release

on:
  push:
    tags:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set env
        run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:10})
      - name: Docker build cache
        uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
        with:
          key: magento2-dev-docker-cache-{hash}
          restore-keys: |
            magento2-dev-docker-cache-
      - name: Docker Login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Copy .env.sample to .env
        run: cp .env.sample .env
      - name: For php8.1
        run: PHP_VERSION=8.1 DOCKER_TAG=$RELEASE_VERSION docker-compose -f docker-compose-publish.yml build && PHP_VERSION=8.1 DOCKER_TAG=$RELEASE_VERSION docker-compose -f docker-compose-publish.yml push
      - name: For php8.0
        run: PHP_VERSION=8.0 DOCKER_TAG=$RELEASE_VERSION docker-compose -f docker-compose-publish.yml build && PHP_VERSION=8.0 DOCKER_TAG=$RELEASE_VERSION docker-compose -f docker-compose-publish.yml push
      - name: For php7.4
        run: PHP_VERSION=7.4 DOCKER_TAG=$RELEASE_VERSION docker-compose -f docker-compose-publish.yml build && PHP_VERSION=7.4 DOCKER_TAG=$RELEASE_VERSION docker-compose -f docker-compose-publish.yml push
      - name: For php7.3
        run: PHP_VERSION=7.3 DOCKER_TAG=$RELEASE_VERSION docker-compose -f docker-compose-publish.yml build && PHP_VERSION=7.3 DOCKER_TAG=$RELEASE_VERSION docker-compose -f docker-compose-publish.yml push
      - name: For php7.2
        run: PHP_VERSION=7.2 DOCKER_TAG=$RELEASE_VERSION docker-compose -f docker-compose-publish.yml build && PHP_VERSION=7.2 DOCKER_TAG=$RELEASE_VERSION docker-compose -f docker-compose-publish.yml push
      - name: For php7.1
        run: PHP_VERSION=7.1 DOCKER_TAG=$RELEASE_VERSION docker-compose -f docker-compose-publish.yml build && PHP_VERSION=7.1 DOCKER_TAG=$RELEASE_VERSION docker-compose -f docker-compose-publish.yml push
